### ISSUE TITLE
Accessibility 89% & SEO 50%

### ISSUE THREAD

**Issue by gminova** [fac-17/W3-Partyps#37]
1. Input field => Background and foreground colors do not have a sufficient contrast ratio.
2. Document doesn't have a <title> element
3. Document doesn't have <meta name="viewport"> tag with width or initial-scale
4. Document doesn't use legible font sizes
Text is illegible because there's no viewport meta tag optimized for mobile screens.
5. Tap targets are not sized appropriately
Tap targets are too small because there's no viewport meta tag optimized for mobile screens

**Comment by hrmstockdale** [comment]
Re 1. this [site](https://contrast-ratio.com/#white-on-rgb%28253%2C81%2C121%29) may be useful in resolving this issue, but its also a cracking tool to use when prefiguring colour-schemes for projects in the near future :).
